version: '3.8'
services:
  tmp:
    build: ./Dockerfile
    container_name: tmp
    hostname: tmp
    shm_size: '28gb'
    volumes:
      - ./:/$PWD/:cached
    environment:
      TZ: Asia/Tokyo
    tty: true
